image: node:latest
before_script:
  - npm install
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public && mkdir public
    - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
